# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caebc623b02d6ef1f50926c7762b78704ec604003687d7f84b4387d37c3c55416c1e58481251ca8657dc425a74ade27715e1de3d86cade78080cab577ea2db9c

test:
  secret_key_base: 4e6d4fad496e043f55af0ce8ee5c335a0fbf9653ba24ec7683e5225136c47e1c2aee582948b9a044ef1579fb656cbabf933f855b777d8598f3e57a02ecca00ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
